export const data = {
  edges: [
    [0, 2],
    [1, 3],
    [2, 4],
    [3, 5],
    [4, 6],
    [5, 6],
  ],
  nodes: [
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 0,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 1 },
        src0: { kind: "none", value: 0 },
        src1: { kind: "none", value: 0 },
        literal: 32,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 0,
      last_pc: 0,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 0,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "MEM",
        op: "mov",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 2 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 1,
      last_pc: 1,
    },
    {
      instruction: {
        format: "ALU",
        op: "add",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 0,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "ALU",
        op: "add",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "reg", value: 3 },
        src0: { kind: "reg", value: 1 },
        src1: { kind: "reg", value: 2 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 2,
      last_pc: 2,
    },
    {
      instruction: {
        format: "MEM",
        op: "st",
        dtype: "u32",
        mod: { abs: false, neg: false, clamp: false, omod: 0 },
        flags: { trace: false },
        dst: { kind: "mem", value: 2 },
        src0: { kind: "reg", value: 3 },
        src1: { kind: "none", value: 0 },
        literal: 0,
      },
      thread: 0,
      cluster: 0,
      SM: 1,
      pc: 3,
      last_pc: 3,
    },
  ],
};
